### ISSUE TITLE
Code/Peer Review

### ISSUE THREAD

**Issue by sparemind** [weifanjiang/Nullness_Lite#10]
I reviewed the commit history of the master branch in [the main fork](https://github.com/979216944/checker-framework) as well as the documentation present in the [project repo](https://github.com/weifanjiang/Nullness_Lite).

- It's unclear whether the NullnessLite specific tests (.../nullness-liteoption/*) test for the catching of desired nullness errors or for the missing of undesired ones. NullnessLiteInit1 indicates expected errors for features that should be disabled and NullnessLiteInvalidDataflow1 has no such indications. If both are being tested, labelling which tests are testing for functionality and which are testing for lack thereof would be helpful.

- Tests seem to do a good job of covering all of the four features being disabled. I'm not familiar with how much the checker framework is involved with initialization checks and how much it needs testing, but the NullnessLiteInit tests seem sparse compared to the others.

- Good use of an issue tracker. Are the issue logs in the two separate repositories different in some way? It may be worth consolidating them to one place if not so that they can be more easily referenced.

- Pull request workflow is very clear. The request discussions and references to issues in the tracker give a good sense of the history of how problems are approached and fixed.

- Typo in README.md section title: 'IntelliJ (**wihout** "Infer Nullity" before...'

**Comment by Alicewillbe** [comment]
Thank you for the feedback.

> It's unclear whether the NullnessLite specific tests (.../nullness-liteoption/*) test for the catching of desired nullness errors or for the missing of undesired ones. 
> I'm not familiar with how much the checker framework is involved with initialization checks and how much it needs testing, but the NullnessLiteInit tests seem sparse compared to the others.

We will take your advice to imporve our tests files to be more pinpoint and descriptive about why we design test in some way. The new commit will be updated in this comment shortly.

> Typo in README.md section title: 'IntelliJ (wihout "Infer Nullity" before...'

Thanks for reporting the typo! We fixed it now.

**Comment by Alicewillbe** [comment]
Tests updated: [link](https://github.com/979216944/checker-framework/pull/10)
Since no further comments added, we close the issue now.
