### ISSUE TITLE
Feedback for peer review holistics

### ISSUE THREAD

**Issue by Ahd2112** [weifanjiang/Nullness_Lite#9]
## Review for Nullness_Lite ##
- It looks like you are all using code review to a great extent with assigning pull requests and haveing code review groups.
- You are using the issue tracker to identify bugs
- I cant tell how your work flow has been, I see that some of you have also forked the checker framework and made some changes, was this part of the project?
  or something you did before. Is there one central repository at 979216944/checker-framework that you all work on?
- I see lots of communication in pull requests.
- Looks like a lot of work has gone into testing the changes you have made to implement nullness_lite

I decided to review the merges you did with the master branch to see the bulk of the changes that were committed all at once. I read the issue tracker logs
as well to see what work had been happening there. I also read the documentation in the https://github.com/weifanjiang/Nullness_Lite repo

**Comment by Alicewillbe** [comment]
Thank you for the feedback.
> I cant tell how your work flow has been, I see that some of you have also forked the checker framework and made some changes, was this part of the project?
> or something you did before. Is there one central repository at 979216944/checker-framework that you all work on?

We only make implementation on one fork, which is 979216944/checker-framework.

**Comment by Alicewillbe** [comment]
Since no further comments added, we close the issue now.
